name: Salesforce DX Install Test
on:
    [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'node:13.1-alpine'
    # Check install
    steps:
      - name: Install Salesforce CLI
        run: |
          export DEV_DEBUG=true
          export SFDX_INSTALLER=false
          apk add --no-cache bash
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
          ./sfdx/install